name: golangci-lint

on:
  push:
    branches: [ main, release-** ]
  pull_request:
    branches: [ main, release-** ]
  workflow_dispatch:

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
 EXCLUDE_ENTERPRISE: true

jobs:
  down-migrations:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          path: "focalboard"
      - name: assert that down migrations are SELECT 1 scripts
        run: |
          cd focalboard
          echo 'SELECT 1;' > downmigration
          for file in server/services/store/sqlstore/migrations/*.down.sql; do diff -Bw downmigration $file; done

  golangci:
    name: plugin
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
        with:
          go-version: 1.21
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          path: "focalboard"
      - name: set up golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.59.0
      - name: lint
        run: |
          cd focalboard
          make server-lint
